### ISSUE TITLE
Typo in help dialog

### ISSUE THREAD

**Issue by Augustifolia** [fireclawthefox/DirectGuiDesigner#20]
This is a very minor issue, but the help dialog claims that the keyboard-event `control-delete` can be used to delete objects. Destroying objects is actually bound to just `delete` instead. What would you consider to be the expected behaviour?

**Comment by fireclawthefox** [comment]
Need to check that tomorrow what I had in mind for that. I think it was to prevent accidental deletions when the user is in a textfield and only wants to delete a character in it.
