### ISSUE TITLE
Issue with expanding list and tuple properties in the properties panel

### ISSUE THREAD

**Issue by Augustifolia** [fireclawthefox/DirectGuiDesigner#23]
When adding an entry to a list or tuple property the property panel is refreshed and the new entry is removed. By updating the sections of the panel, instead of refreshing the panel every time an entry is added, the issue is resolved.
In other words, do this:
```
            if updateMainBox:
                entriesBox.refresh()
                for section, boxFrame in self.boxFrames.items():
                    boxFrame.refresh()
                    self.updateSection(section)
                    section.toggleCollapsed()
                    section.toggleCollapsed()
```
and remove the line:
`self.resizeFrame()`

**Comment by Augustifolia** [comment]
If you want, I can create a PR?

**Comment by fireclawthefox** [comment]
A PR is always welcome.

Maybe we can also somehow fix whatever caused the duplicate call for section.toggleCollapsed()
