### ISSUE TITLE
Issues with undoing copy and cut events

### ISSUE THREAD

**Issue by Augustifolia** [fireclawthefox/DirectGuiDesigner#25]
Cutting and pasting elements does not currently support undoing. We should probably add a call to the kill ring in the method `pasteCutElement`.

If you copy an element (1) onto another element (2) and then tries to undo a couple of times the application crashes. Specifically undoing the creation of element (2) seems to be the issue.
Here is the log file for the that issue:
[DirectGuiDesigner.log](https://github.com/fireclawthefox/DirectGuiDesigner/files/12440281/DirectGuiDesigner.log)

**Comment by fireclawthefox** [comment]
It seems to store the wrong value somewhere for the workOn.editObject according to the exception in the log file. I sadly won't be able to check it during the weekend but next week I may have time again. In case you want to look for yourself, I can try to guide you to the locations where the kill-ring does it's things.

**Comment by Augustifolia** [comment]
It would be nice to understand how the kill ring works, but I am also busy until sometime next week. We can deal with this when we have time, I'm in no rush

**Comment by Augustifolia** [comment]
It seems like pasting generates three KillRing events: adding the new element, copying the properties from the old element, and the actual copy element event. I'm inclined to just add an argument to `__copyOptions` and `__createControl` to allow skipping the calls to the KillRing.

**Comment by Augustifolia** [comment]
Just pushed a fix for both of these issues to PR #24
