### ISSUE TITLE
Unknown options when making an OkCancelDialog

### ISSUE THREAD

**Issue by azizalbastaki** [fireclawthefox/DirectGuiDesigner#3]
Hello, I've started using your GUI editor and it's amazing, well done!

Just a potential bug that I may have discovered, when creating an Ok/Cancel dialog and exporting it into Python code, I get this error: 
`KeyError: 'Unknown options "Button_borderWidth, Button_frameSize, Button_hpr, Button_pad, Button_pos, Button_text" for OkCancelDialog'`.

Looking at the code, I have noticed that there are parameters for both `Button` and `Button0`, I didn't get errors for `Button0` and I seem to have fixed this by replacing all `Button`s with `Button1`. Here is the full working code for my modified code:
```
class GUI:
    def __init__(self, rootParent=None):
        
        self.pg125 = OkCancelDialog(
            frameSize=(-0.3324999973643571, 0.3324999973643571, -0.34249999769032, 0.19224999830126763),
            hpr=LVecBase3f(0, 0, 0),
            pos=LPoint3f(0, 0.1, 0.025),
            state='normal',
            text='Ok/Cancel Dialog',
            Button1_borderWidth=(0.01, 0.01),
            Button1_frameSize=(-0.09699999749660491, 0.10150000661611557, -0.016750000640749933, 0.05349999874830246),
            Button1_hpr=LVecBase3f(0, 0, 0),
            Button1_pad=(0.01, 0.01),
            Button1_pos=LPoint3f(-0.109175, 0, -0.21575),
            Button1_text='Cancel',
            Button0_text_align=TextNode.A_center,
            Button0_text_scale=(0.06, 0.06),
            Button0_text_pos=(0, 0),
            Button0_text_fg=LVecBase4f(0, 0, 0, 1),
            Button0_text_bg=LVecBase4f(0, 0, 0, 0),
            Button0_text='Ok',
            text_align=TextNode.A_left,
            text_scale=(0.06, 0.06),
            text_pos=(-0.23549999739043415, -0.012749999761581421),
            text_fg=LVecBase4f(0, 0, 0, 1),
            text_bg=LVecBase4f(0, 0, 0, 0),
            parent=rootParent,
        )
        self.pg125.setTransparency(0)


    def show(self):
        self.pg125.show()

    def hide(self):
        self.pg125.hide()

    def destroy(self):
        self.pg125.destroy()

gui = GUI()

gui.show()

```

**Comment by fireclawthefox** [comment]
Thanks for the report, I'll take a look into this.

If you haven't changed any of the buttons values manually and don't intend to do so, you could even try to remove all those lines which also results in a cleaner file. There seem to be a few problems with the detection of changed variables in DirectGui widgets, so this may need some extras within the DirectGui system. In the meantime I may be able to provide a workaround in the exporter classes.

**Comment by fireclawthefox** [comment]
This issue should now be solved. The designer will now write out all states of each component and not omit the numbers. This may make the resulting python scripts a bit more lengthy and not as clean as hand written ones, but it should ensure that the resulting design looks like in the designer. This also will be used once the designer can handle the multiple states of a component.

In case the problem reoccurs or other issues come up with this change, please reopen this report or fill a new one.
