### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by janEntikan** [fireclawthefox/DirectGuiDesigner#4]
To err is human, and I have developed a compulsive reflex to hit ctrl-z when I inevitably ruin progress.

**Comment by fireclawthefox** [comment]
The new feature has now been added. You can undo, redo and switch between redo branches to not loose any state that's supported by the undo tree yet. The newly assigned keyboard shortcuts are stated in the help window and the readme.

Note, while most property changes and edits (like removing, copying, moving) are supported, some actions may not yet be supported by this feature. If you find any specific feature missing to be undoable, please let me know.
